version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - postgre_data:/var/lib/postgresql/data
    ports:
      -  "${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    env_file:
      - .env

  nginx:
    container_name: nginx
    build: ./nginx
    image: mysite/nginx
    restart: always
    ports: 
      - "8080:80"
    volumes:
      - ./mysite:/srv/mysite
      - ./log:/var/log/nginx
    depends_on:
      - django

  django:
    container_name: django
    build: ./mysite
    image: mysite/django
    restart: always
    command: uwsgi --ini uwsgi.ini 
    volumes:
      - ./mysite:/srv/mysite
      - ./log:/var/log/uwsgi
    depends_on:
      - db
    env_file:
      - .env

  django_debug:
    container_name: django_debug    
    build: ./mysite
    image: mysite/django/debug
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/srv/mysite
    ports:
      - 8000:8000
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env.debug

volumes:
  postgre_data: